# Generated by Django 4.2.6 on 2023-10-21 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(unique=True)),
                ('stage', models.CharField(choices=[('swiss', 'Swiss Stage'), ('knockout', 'Knockout Stage'), ('final', 'Final')], default='swiss', max_length=255)),
                ('best_of', models.IntegerField(choices=[(1, 'BO1'), (3, 'BO3'), (5, 'BO5')], default=1)),
                ('result', models.CharField(blank=True, max_length=10, null=True)),
                ('bet_history', models.JSONField(blank=True, default=list, null=True)),
            ],
            options={
                'verbose_name_plural': 'matches',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('acronym', models.CharField(max_length=10)),
                ('base_pr', models.FloatField()),
                ('current_pr', models.FloatField()),
                ('pr_history', models.JSONField(blank=True, default=list, null=True)),
                ('seed', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')])),
                ('origin', models.CharField(choices=[('lck', 'LCK'), ('lcs', 'LCS'), ('lec', 'LEC'), ('lpl', 'LPL'), ('vcs', 'VCS')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('balance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MatchTeamRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_team1', models.BooleanField()),
                ('is_winner', models.BooleanField(blank=True, null=True)),
                ('match_score', models.CharField(blank=True, max_length=10, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match_bet.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match_bet.team')),
            ],
            options={
                'unique_together': {('team', 'match')},
            },
        ),
        migrations.AddField(
            model_name='match',
            name='teams',
            field=models.ManyToManyField(related_name='matches', through='match_bet.MatchTeamRelation', to='match_bet.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_winners', to='match_bet.team'),
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odds', models.FloatField()),
                ('stake', models.FloatField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match_bet.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match_bet.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match_bet.user')),
            ],
        ),
    ]
