# Generated by Django 4.2.6 on 2023-10-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_bet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='current_odds',
            field=models.JSONField(blank=True, default=tuple, null=True),
        ),
    ]
