# Generated by Django 4.2.6 on 2023-10-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_bet', '0002_match_current_odds'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchteamrelation',
            name='pr_delta',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
