# Generated by Django 4.2.6 on 2023-10-21 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match_bet', '0003_matchteamrelation_pr_delta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='bet_history',
            new_name='odds_history',
        ),
    ]
