# Generated by Django 4.2.6 on 2023-10-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_bet', '0004_rename_bet_history_match_odds_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_concluded',
            field=models.BooleanField(default=False),
        ),
    ]
