# Generated by Django 4.2.6 on 2023-10-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_bet', '0005_match_is_concluded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='best_of',
            field=models.IntegerField(choices=[(1, 'BO1'), (3, 'BO3'), (5, 'BO5')], default=5),
        ),
    ]
